root: LOG_PATH
exp_name: "exp"
model: "tic_promptmodel_first2"
dataset: "coco"
dataset_path: DATASET_PATH
maskrcnn_path: MASKRCNN_PATH_FROM_DETECTRON2
checkpoint: CHECKPOINT_PATH  # could be pre-trained base codec (for training) or trained TransTIC (for evaluation)
epochs: 40
learning_rate: 1.e-4
num_workers: 4
quality_level: 1 # {1,2,3,4}
lmbda:  0.0018 # {0.0018, 0.0035, 0.0067, 0.013}
batch_size: 8
test_batch_size: 1
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
gpu_id: 0
save: True
clip_max_norm: 1.0
seed: 42
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
VPT_lmbda: 2 # {2, 1, 0.5, 0.2}
WINDOW: 'same'
HYPERPRIOR: False
RETURN_ATTENTION: False
MODEL_DECODER: False
MASK_DOWNSAMPLE: 2
DECODER_BLOCK: [1,2,3,4]
